/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorsensores;

import java.io.DataInputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ramyllo
 */
public class Monitor extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    public Monitor() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sensor1 = new javax.swing.JLabel();
        sensor2 = new javax.swing.JLabel();
        sensor3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dispositivo 1");

        jLabel2.setText("Dispositivo 2");

        jLabel3.setText("Dispositivo 3");

        media.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        media.setForeground(new java.awt.Color(0, 187, 187));
        media.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        media.setText("00");

        jLabel5.setText("Média Sensores");

        sensor1.setForeground(new java.awt.Color(120, 122, 187));
        sensor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sensor1.setText("00");

        sensor2.setForeground(new java.awt.Color(187, 187, 0));
        sensor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sensor2.setText("00");

        sensor3.setForeground(new java.awt.Color(187, 0, 187));
        sensor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sensor3.setText("00");

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(media, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sensor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sensor2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(sensor3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensor1)
                    .addComponent(sensor2)
                    .addComponent(sensor3))
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(media)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitor().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel media;
    private javax.swing.JLabel sensor1;
    private javax.swing.JLabel sensor2;
    private javax.swing.JLabel sensor3;
    // End of variables declaration//GEN-END:variables

    public void monitorSensores(String[] valores) {
        //media.setText(Integer.toString(valores));

        sensor1.setText(valores[0]);
        sensor2.setText(valores[1]);
        sensor3.setText(valores[2]);

        double mediaValores = (Double.parseDouble(valores[0])
                + Double.parseDouble(valores[1])
                + Double.parseDouble(valores[2])) / 3;

        media.setText(Double.toString(mediaValores));
    }

    /*
    public static void teste() throws IOException {
        ServerSocket servidor = new ServerSocket(1234);

        while (true) {

            Socket cliente1 = new Socket();
            Socket cliente2 = new Socket();
            Socket cliente3 = new Socket();

            try {
                cliente1 = servidor.accept();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }

            try {
                cliente2 = servidor.accept();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }

            try {
                cliente3 = servidor.accept();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }

            DataInputStream fluxo_entrada1 = new DataInputStream(cliente1.getInputStream());
            DataInputStream fluxo_entrada2 = new DataInputStream(cliente2.getInputStream());
            DataInputStream fluxo_entrada3 = new DataInputStream(cliente3.getInputStream());

            String s1 = fluxo_entrada1.readUTF();
            String s2 = fluxo_entrada2.readUTF();
            String s3 = fluxo_entrada3.readUTF();

        }

    }  */
}
